#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo rm /etc/nginx/sites-available/default.html
sudo echo 'Hello World' >> /etc/nginx/sites-available/default.html
sudo /etc/init.d/nginx restart
