#!/usr/bin/env bash
# display To infinity and beyond indefinitely
# shellcheck disable=SC2009
MYPID=$( ps faux | grep '4-to_infinity_and_beyond' | grep -vw grep | awk '{ print $2 }' );
kill -9 "${MYPID}";
